server:
  port: 8787
spring:
  application:
    name: qafordevs-reactive

  r2dbc:
    url:  r2dbc:postgresql://localhost:5432/qafordevs_reactive
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/qafordevs_reactive
    user: postgres
    password: postgres
